### ISSUE TITLE
`ts (6307)` error in typescript-vue-plugin v1.8.1

### ISSUE THREAD

**Issue by yaegassy** [yaegassy/coc-typescript-vue-plugin#1]
## Error

**capture**:

<img width="853" alt="coc-typescript-vue-plugin-issue-1-1" src="https://github.com/yaegassy/coc-typescript-vue-plugin/assets/188642/4fa656da-1c84-40f0-98da-612a7afaee8e">

## Same error occurs in cases where the TypeScript Vue Plugin extension is not used in VSCode

**capture**:

<img width="1074" alt="coc-typescript-vue-plugin-issue-1-2" src="https://github.com/yaegassy/coc-typescript-vue-plugin/assets/188642/e12e8725-671c-421d-89dc-2a31c3d097b2">

- `typescript-vue-plugin` package already installed in workspace (project).

- Already configured plugin in `tsconfig.app.json` below.

  ```jsonc
  {
    "extends": "@vue/tsconfig/tsconfig.dom.json",
    "include": ["env.d.ts", "src/**/*", "src/**/*.vue"],
    "exclude": ["src/**/__tests__/*"],
    "compilerOptions": {
      "composite": true,
      "baseUrl": ".",
      "paths": {
        "@/*": ["./src/*"]
      },
      "plugins": [
        {
          "name": "typescript-vue-plugin"
        }
      ]
    }
  }
  ```

- Already configured to use typescript v5.0.4 in workspace.

**Comment by johnsoncodehk** [comment]
It's fixed by https://github.com/volarjs/volar.js/commit/0df1bb129ae99440b2909ed89add3d9aa8aafd5f but not been released for `typescript-vue-plugin` yet.

**Comment by yaegassy** [comment]
Hi, @johnsoncodehk . Thanks for checking the issue in this repository 🙇🙇🙇.
